"""replies go one level deep

Adds ``comments.parent_id``: what a comment is a reply to, or NULL for
something said to the post itself.

Nullable, so every row that already exists is a top-level comment — which is
what they are. No backfill, no default, and no table rewrite.

The foreign key points at the same table and cascades, so a comment that goes
takes the replies to it with it, whoever issued the DELETE. It is **named**
rather than left to Postgres: an autogenerated name is fine going up and is a
guess going down, and `drop_constraint(None, ...)` is not a thing that works.

The one-level rule is not here. A database check constraint could express it —
"parent_id must point at a row whose own parent_id is NULL" needs a trigger or
a redundant column, neither of which is worth it — so the depth lives in the
schema (`ReplyOut` has no replies) and in one check in the create handler.

Revision ID: 1d54654b9387
Revises: a7d2e4f60b11
Create Date: 2026-09-19 14:26:27.469690

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "1d54654b9387"
down_revision: Union[str, Sequence[str], None] = "a7d2e4f60b11"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FK = "fk_comments_parent_id_comments"


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column("comments", sa.Column("parent_id", sa.Integer(), nullable=True))
    op.create_index("ix_comments_parent_id", "comments", ["parent_id"], unique=False)
    op.create_foreign_key(
        FK, "comments", "comments", ["parent_id"], ["id"], ondelete="CASCADE"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(FK, "comments", type_="foreignkey")
    op.drop_index("ix_comments_parent_id", table_name="comments")
    op.drop_column("comments", "parent_id")
